# Generated by Django 4.1.7 on 2023-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=20)),
                ('transaction_code', models.CharField(max_length=20)),
                ('narration', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('account_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('actual_balance', models.CharField(max_length=20)),
                ('available_balance', models.CharField(max_length=20)),
            ],
        ),
    ]
