# Generated by Django 4.1.7 on 2023-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
