# Generated by Django 4.1.7 on 2023-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_transaction_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='actual_balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='available_balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
